export const CALCULATOR_BUTTONS = [
    { id: "left-parenthesis", text: "(", type: "special" },
    { id: "right-parenthesis", text: ")", type: "special" },
    { id: "sign", text: "±", type: "special" },
    { id: "clear", text: "C", type: "service" },
    { id: "backspace", text: "⌫", type: "service" },
    { id: "seven", text: "7", type: "digit" },
    { id: "eight", text: "8", type: "digit" },
    { id: "nine", text: "9", type: "digit" },
    { id: "divide", text: "÷", type: "operator" },
    { id: "power", text: "xⁿ", type: "special" },
    { id: "four", text: "4", type: "digit" },
    { id: "five", text: "5", type: "digit" },
    { id: "six", text: "6", type: "digit" },
    { id: "multiply", text: "×", type: "operator" },
    { id: "sqrt", text: "√", type: "special" },
    { id: "one", text: "1", type: "digit" },
    { id: "two", text: "2", type: "digit" },
    { id: "three", text: "3", type: "digit" },
    { id: "subtract", text: "-", type: "operator" },
    { id: "equals", text: "=", type: "service" },
    { id: "zero", text: "0", type: "digit" },
    { id: "decimal", text: ".", type: "special" },
    { id: "percent", text: "%", type: "special" },
    { id: "add", text: "+", type: "operator" }
];